---
# tasks file for nginx-docker

- name: Get dockerhost
  shell: /sbin/ip route | awk '/docker0/ { print $NF }'
  register: dockerhost_response

- set_fact:
    dockerhost_ip:    "{{ dockerhost_response.stdout }}"

- name:    "Setup config folder"
  file:
    path:  "{{ nginx_config_dir }}"
    state: directory
    mode:  0777
  become:  yes

- name:    "Create nginx config"
  template:
    src:   templates/balanced.nginx.conf.j2
    dest:  "{{ nginx_config_dir }}/nginx.conf"
  become:  no
  notify: restart_nginx_container

- name: "Pull Orthanc image - nginx:{{ nginx_docker_image_tag }}"
  docker_image:
    name: 'nginx'
    tag:  '{{ nginx_docker_image_tag }}'

- name: Setup nginx container
  docker_container:
    name:  "{{ nginx_container_name }}"
    image: "nginx:{{ nginx_docker_image_tag }}"
    state: started
    ports: ["80:80", "443:443"]
#    links:        "{{ r_proxies.keys() }}"
    volumes:
      - "{{ nginx_config_dir }}/nginx.conf:/etc/nginx/nginx.conf:ro"
#      - "{{ secure.cert_dir }}:{{ secure.cert_dir }}"

  register: nginx_container

- meta: flush_handlers

- name: Wait until nginx is available
  wait_for: port=80 delay=3
  when: nginx_container.changed